### ISSUE TITLE
Env vars setup

### ISSUE THREAD

**Issue by Dynnammo** [cap-collectif/cap-collectif#7]
As an admin sys, I would like to setup a selp-hosted platform of cap-collectif.

However, an important part of the processus relies on the setup of env variable, but this part is not documented in the Docusaurus : https://developers.cap-collectif.com/getting-started/environment-variables.

- [ ] Add a commented `.env.example` to the project
- [ ] Documenting each variable to be provided in the documentation website

**Comment by simonaszilinskas** [comment]
Already heard from multiple people that they failed to run cap-collectif without the env variables documentation.

**Comment by spyl94** [comment]
Hey,

We don't have a `.env.example` file,  you can generate a default `.env.local` file using `fab local.app.setup-default-env-vars` (fixed by https://github.com/cap-collectif/cap-collectif/pull/8).

I added a start of documentation https://developers.cap-collectif.com/getting-started/environment-variables

But more importantly, we just made the repository https://github.com/cap-collectif/developers public, so you can help us provide some documentation !

**Comment by Dynnammo** [comment]
> Hey,
> 
> We don't have a `.env.example` file, you can generate a default `.env.local` file using `fab local.app.setup-default-env-vars` (fixed by #8).
> 
> I added a start of documentation https://developers.cap-collectif.com/getting-started/environment-variables
> 
> But more importantly, we just made the repository https://github.com/cap-collectif/developers public, so you can help us provide some documentation !

With pleasure ! I'll try to look at it this month !
